### ISSUE TITLE
Export Family

### ISSUE THREAD

**Issue by julillosamaral** [cityzenith/Revit2Gltf#3]
Sorry to put this as an issue.

Is it possible to export the gltf of a family document?

Thanks,
Julio

**Comment by lelandjobson** [comment]
Hey @julillosamaral 

I haven't tried it on a family document file, only model files. Did the command fail when you ran it on the family?

**Comment by julillosamaral** [comment]
I think I used this project as a base for what I did but I wasn't able to use it as a library and only do the export. So we could say that it is possible to make it work on a family document.

Thanks,
